services:
  sgptools:
    image: itskalvik/sgp-tools:beta
    build:
      context: ./
      platforms:
          - "linux/arm64"
          - "linux/amd64"
      dockerfile: robot-docker/Dockerfile
      args:
        - ROS_DISTRO=jazzy

    # Enabling GPU access with Compose
    # https://docs.docker.com/compose/gpu-support/
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #          - capabilities: [gpu]
    #            count: all

    environment:
      # Set a fancy prompt (See ~/.bashrc in the container)
      - TERM=xterm-256color

    volumes:
      - ./ros2_ws/src:/root/ros2_ws/src
      - /dev:/dev
      - /var/run/dbus:/var/run/dbus

    ports:
      - "4717:4717"

    #network_mode: host
    privileged: true
    tty: true
    stdin_open: true