services:
  sgptools:
    image: itskalvik/sgp-tools:0.0.1
    build:
      context: ./
      platforms:
          - "linux/amd64"
          - "linux/arm64"
      dockerfile: robot-docker/Dockerfile
      args:
        - ROS_DISTRO=humble

    # Enabling GPU access with Compose
    # https://docs.docker.com/compose/gpu-support/
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #          - capabilities: [gpu]
    #            count: all

    environment:
      # Set a fancy prompt (See ~/.bashrc in the container)
      - TERM=xterm-256color

    volumes:
      - ./ros2_ws/src:/home/ros2_ws/src
      - /dev:/dev
      - /var/run/dbus:/var/run/dbus

    network_mode: host
    privileged: true