services:
  sgptools:
    image: itskalvik/sgp-tools:simulator
    runtime: nvidia
    build:
      context: ./
      platforms:
          - "linux/amd64"
      dockerfile: sim-docker/Dockerfile
      args:
        - ROS_DISTRO=jazzy
        - GZ_VERSION=harmonic

    environment:
      # ROS settings
      - RCUTILS_COLORIZED_OUTPUT=1

      # Set a fancy prompt (See ~/.bashrc in the container)
      - TERM=xterm-256color
      - NVIDIA_VISIBLE_DEVICES=all

      # WSLg settings
      # https://www.reddit.com/r/bashonubuntuonwindows/comments/n2nthu/can_i_use_the_new_wslg_with_docker/
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER

    volumes:
      - ./ros2_ws/src:/home/ubuntu/ros2_ws/src
      - /dev:/dev

      # WSLg settings
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix

    network_mode: host
    privileged: true