name: pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'same-as-branch-mentioned-above'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: sitl-docker/Dockerfile
          push: true
          tags: itskalvik/sgp-tools:sitl-humble-garden
          platforms: linux/amd64,linux/arm64

      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: robot-docker/Dockerfile
          push: true
          tags: itskalvik/sgp-tools:robot-humble
          platforms: linux/amd64,linux/arm64