name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  bake-robot:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push robot container
        uses: docker/bake-action@v5
        with:
          push: true
          files: ./robot-compose.yml
          set: sgptools.platform=linux/amd64,linux/arm64

  bake-sitl:
    runs-on: ubuntu-latest
    steps:
      - name: "Free up disk space"
        run: |
          sudo apt-get -qq purge build-essential ghc*
          sudo apt-get clean
          docker system prune -af
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          df -h /
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push sitl container
        uses: docker/bake-action@v5
        with:
          push: true
          files: ./sitl-compose.yml
          set: sgptools.platform=linux/amd64,linux/arm64
