name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push robot container
        uses: docker/bake-action@v5
        with:
          push: true
          files: ./robot-compose.yml
          set: target.platform=linux/amd64,linux/arm64
      -
        name: Build and push sitl container
        uses: docker/bake-action@v5
        with:
          push: true
          files: ./sitl-compose.yml
          set: target.platform=linux/amd64,linux/arm64